//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteParse.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiteParse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_64 {
            get {
                object obj = ResourceManager.GetObject("info_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формирование векторов произведено с ошибкой. Попробуйте еще раз.
        /// </summary>
        internal static string InfoForm_distanceBtn_Click_Формирование_векторов_произведено_с_ошибкой__Попробуйте_еще_раз {
            get {
                return ResourceManager.GetString("InfoForm_distanceBtn_Click_Формирование_векторов_произведено_с_ошибкой__Попробуйт" +
                        "е_еще_раз", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page is not available.
        /// </summary>
        internal static string ParseForm_GetHtml_Page_is_not_available {
            get {
                return ResourceManager.GetString("ParseForm_GetHtml_Page_is_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Вес = .
        /// </summary>
        internal static string ParseForm_TermFrequencyMethod_ {
            get {
                return ResourceManager.GetString("ParseForm_TermFrequencyMethod_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данная страница уже добавлена в БД.
        /// </summary>
        internal static string ParseForm_TermFrequencyMethod_Данная_страница_уже_добавлена_в_БД {
            get {
                return ResourceManager.GetString("ParseForm_TermFrequencyMethod_Данная_страница_уже_добавлена_в_БД", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vector length not equal.
        /// </summary>
        internal static string ParseForm_vectBtn_Click_vector_length_not_equal {
            get {
                return ResourceManager.GetString("ParseForm_vectBtn_Click_vector_length_not_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Согласовать {
            get {
                object obj = ResourceManager.GetObject("Согласовать", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
